### ISSUE TITLE
Feature request - more customization options

### ISSUE THREAD

**Issue by gerchicov-bp** [KeiroMidori/SBMessageInputView#1]
For example `setTextView()` contains corner radius, content insets and font changes which I don't want to use in my project.

`layoutSubviews()` contains even custom corner radius which is impossible to change properly and your control looks like awful with it (ran your example on iphone 5s, ios 12)

**Comment by KeiroMidori** [comment]
@gerchicov-bp thank you for the feedback. Will work on improving customization.
