### ISSUE TITLE
Feature request - resizing delegate methods

### ISSUE THREAD

**Issue by gerchicov-bp** [KeiroMidori/SBMessageInputView#2]
For example in my case I need to move content in table view according to current `textView` height but your control don't send any event about size change. Or should I check `heightConstraint.constant` after each symbol input?

**Comment by KeiroMidori** [comment]
@gerchicov-bp it would be a nice to have to get a delegate method called when the size changes, but indeed, in the meantime you can always check the view size through the textview delegate methods.
