### ISSUE TITLE
Buggy textView initialization

### ISSUE THREAD

**Issue by gerchicov-bp** [KeiroMidori/SBMessageInputView#5]
`UITextView` is created twice - inside both `SBMessageInputView` on creation and `setTextView()`. The only reason you should use that is if you want to use it without constraints but in `setTextView()` you declare constraints, so it should work anyways.

Additional linked bug is you forbid to setup the initial text because the whole text view is recreated. The same is for `mainView` and `button`

**Comment by KeiroMidori** [comment]
@gerchicov-bp Thank you, it's fixed here: https://github.com/KeiroMidori/SBMessageInputView/commit/b4f9d2bb9ea3cffa2a9000c7e22d22ec4d55cd6c
